### ISSUE TITLE
Bug in Fronius GEN24 Documentation

### ISSUE THREAD

**Issue by chrdal** [evcc-io/config#96]
Hi, 

the power value in the documentation (after #)  is correct but in the 213 is wrong. If you run it with the 213 you will receive the error:
[site  ] ERROR 2022/03/08 21:01:31 grid meter: sunspec: 213:0:W not found

If you change it to 203 everything works fine!

Best regards

Symo GEN24 Plus[​](https://docs.evcc.io/docs/Home/#symo-gen24-plus)

Netz
PV
Batterie
meters:
  - name: grid
    type: modbus
    model: sunspec
    uri: 192.0.2.2:502
    id: 200
    power: **213**:W # sunspec model 203 meter

**Comment by premultiply** [comment]
Did you set it to Float output?

**Comment by chrdal** [comment]
Of course no ;) I didn't recognize that I have to do it and it is hard if you don't have the technician password. When I changed to 203 like in the documentation it was working (showing at least some values which are plausible up to now)

**Comment by andig** [comment]
We could offer a float and non-float config both?
